# This file configures the Forestry.io CMS-as-a-Service to integrate
# well with this Jekyll template. For more information, see:
#
#   https://forestry.io/docs/settings/config-files/#site-settings
---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: heading
  label: Content
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
- type: heading
  label: Data
- type: document
  path: _data/contact_info.yaml
  label: Contact Information
  match: "**/*"
- type: document
  path: _data/gallery.yaml
  label: Gallery
  match: "**/*"
- type: document
  path: _data/opening_hours.yaml
  label: Opening Hours
  match: "**/*"
upload_dir: static/images
public_path: "/static/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
